apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
operation:
  initiatedBy:
    automated: true
  retry:
    limit: 5
  sync:
    prune: true
    revision: v1.8.2
    syncOptions:
    - CreateNamespace=true
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: cluster-addons
  source:
    chart: cert-manager
    helm:
      valueFiles:
      - values.yaml
    repoURL: https://charts.jetstack.io
    targetRevision: v1.8.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true