apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: guestbook
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: Guestbook demo app
  destinations:
  - namespace: 'guestbook'
    server: https://kubernetes.default.svc
  sourceRepos:
  - 'https://github.com/kubernetes/examples'