apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: cluster-addons
  source:
    chart: ingress-nginx
    repoURL: https://kubernetes.github.io/ingress-nginx 
    targetRevision: v4.1.3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true