server:
  configEnabled: true
  additionalApplications:
  - name: cluster-addons
    namespace: argocd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    project: cluster-addons
    source:
      repoURL: https://github.com/JamesRamone/argo-demo.git
      targetRevision: HEAD
      path: apps
      directory:
        recurse: true
    destination:
      server: https://kubernetes.default.svc
      namespace: argocd
    syncPolicy:
      automated:
        prune: false
        selfHeal: false
  - name: projects
    namespace: argocd
    destination:
      namespace: argocd
      server: https://kubernetes.default.svc
    project: default
    source:
      path: projects
      repoURL: https://github.com/JamesRamone/argo-demo.git
      targetRevision: HEAD
      directory:
        recurse: true
    syncPolicy:
      automated:
        selfHeal: true
        prune: true

  additionalProjects:
  - name: cluster-addons
    namespace: argocd
    finalizers:
    - resources-finalizer.argocd.argoproj.io
    description: Cluster Addons
    sourceRepos:
    - '*'
    destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: cert-manager
      server: https://kubernetes.default.svc


  